controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_thumb_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_12
      - joint_13
      - joint_14
      - joint_15
  - name: fake_finger_1_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
  - name: fake_finger_2_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_finger_3_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_8
      - joint_9
      - joint_10
      - joint_11
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: thumb
    pose: zeros
  - group: finger_1
    pose: zeros
  - group: finger_2
    pose: zeros
  - group: finger_3
    pose: zeros