arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  # gains:
  #   shoulder_pan_joint: {p: 4500,  d: 220, i: 1, i_clamp: 1}
  #   shoulder_lift_joint: {p: 17000,  d: 250, i: 1, i_clamp: 1}
  #   elbow_joint: {p: 3000,  d: 60, i: 1, i_clamp: 1}
  #   wrist_1_joint: {p: 400,  d: 100, i: 50, i_clamp: 1}
  #   wrist_2_joint: {p: 400,  d: 100, i: 50, i_clamp: 1}
  #   wrist_3_joint: {p: 60,  d: 60, i: 5, i_clamp: 1} 
thumb_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_12
    - joint_13
    - joint_14
    - joint_15
  # gains:
  #   joint_12:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_13:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_14:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_15:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
finger_1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_0
    - joint_1
    - joint_2
    - joint_3
  # gains:
  #   joint_0:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_1:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_2:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_3:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
finger_2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  # gains:
  #   joint_4:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_5:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_6:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
  #   joint_7:
  #     p: 100
  #     d: 1
  #     i: 1
  #     i_clamp: 1
finger_3_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_8
    - joint_9
    - joint_10
    - joint_11
  # gains:
    # joint_8:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1
    # joint_9:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1
    # joint_10:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1
    # joint_11:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1