#Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - robotiq_finger_middle_joint_1
    - robotiq_palm_finger_1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint      
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
  - name: gripper_mode_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotiq_palm_finger_1_joint
      - robotiq_palm_finger_2_joint
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
  gains:
    robotiq_finger_middle_joint_1:
      p: 50
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_middle_joint_2:
      p: 50
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_middle_joint_3:
      p: 50
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_1_joint_1:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_1_joint_2:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_1_joint_3:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_2_joint_1:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_2_joint_2:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
    robotiq_finger_2_joint_3:
      p: 1000
      d: 0.5
      i: 0
      i_clamp: 0
  constraints:
    stopped_velocity_tolerance: 0.0
gripper_mode_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robotiq_palm_finger_1_joint
    - robotiq_palm_finger_2_joint
  gains:
    robotiq_palm_finger_1_joint:
      p: 10500
      d: 0
      i: 0
      i_clamp: 0   
    robotiq_palm_finger_2_joint:
      p: 10500
      d: 0
      i: 0
      i_clamp: 0  
  constraints:
    stopped_velocity_tolerance: 0.0   
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 8000
      d: 50
      i: 10
      i_clamp: 100
    shoulder_lift_joint:
      p: 8000
      d: 50
      i: 10
      i_clamp: 100
    elbow_joint:
      p: 8000
      d: 50
      i: 10
      i_clamp: 100
    wrist_1_joint:
      p: 16000
      d: 0
      i: 0
      i_clamp: 0
    wrist_2_joint:
      p: 16000
      d: 0
      i: 0
      i_clamp: 0
    wrist_3_joint:
      p: 16000
      d: 0
      i: 0
      i_clamp: 0     
  constraints:
    stopped_velocity_tolerance: 0.0
